### ISSUE TITLE
Problem naming individual fonts in font collections

### ISSUE THREAD

**Issue by foolnotion** [ToxicFrog/Ligaturizer#23]
Hi,

I was trying to ligaturize Microsoft's Consolas font, which comes as a collection of ttf files:
- consola.ttf (regular)
- consolai.ttf (italic)
- consolab.ttf (bold)
- consolaz.ttf (bold italic)

All the original ttf files have the same font name, "Consolas", however the liga versions have their names wrong: consola, consolai, consolab, consolaz instead of "Consolas", therefore the font no longer works as a collection.

**Comment by ToxicFrog** [comment]
At present it infers the font name from the filename, which usually works, but assumes that font collections use the `<face>-<weight>` naming scheme, e.g. `Consolas-Regular.ttf` and `Consolas-Italic.ttf` rather than `consola.ttf` and `consoli.ttf`.

I have a fix in the works that uses the metadata already present in the font and ignores the filename, I just keep getting preempted by non-programming stuff. I'll make sure it works properly with Consolas.
