### ISSUE TITLE
Blurred outline on ligatures 

### ISSUE THREAD

**Issue by orenmizr** [ToxicFrog/Ligaturizer#37]
first, thanks for this project.
installed the ligatures on **consolas**. but it looks somewhat blurry (win10 + vscode)

![too blurry](https://i.imgur.com/oTjlndQ.png) 

is there a fix ? looking for consolas with good ligatures. thanks

**Comment by rajadain** [comment]
I would also love Consolas with proper ligatures. I'm not sure, but I think the reason these are blurry is because Fira Code is not type-hinted the same way Consolas is, so since Fira Code itself looks blurry on Windows, so do its ligatures when applied to Consolas.

**Comment by antonovicha** [comment]
Have similar problem: VSCode + Win10 -> blurry Liga Consolas ligatures:
![image](https://user-images.githubusercontent.com/16748238/43717032-7f77e5aa-9986-11e8-9079-b2cbbab8df4a.png)
Clean looking Fira Code:
![image](https://user-images.githubusercontent.com/16748238/43717046-8a29ac0e-9986-11e8-942a-ce7589d955c5.png)

@rajadain Fira Code is rendered correctly for me, as you can see in screenshot.

**Comment by ToxicFrog** [comment]
Are they still blurry at different font sizes? What if you generate the font with `--scale-character-glyphs-threshold=2.0`? I'm wondering if this is a font rendering issue or an issue with the ligature scaling feature.

**Comment by ToxicFrog** [comment]
Looking at the way the lines are blurred, it might also be an issue with the *vertical* scaling; horizontal scaling only happens (by default) if the target font disagrees heavily with Fira Code on what the em width is, but the ligatures are always vertically scaled to match the em height of the target. What happens if you comment out line 58 (`self.firacode.em = self.font.em`) and run it with `--scale-character-glyphs-threshold=2.0`? That should disable all scaling, vertical and horizontal; the glyphs might look off-center, but if that fixes the blurring then the centering can always be fixed and vertical scaling made optional.

**Comment by antonovicha** [comment]
@ToxicFrog Here is the results of Consolas conversion:
Only `--scale-character-glyphs-threshold=2.0`:
![image](https://user-images.githubusercontent.com/16748238/44781222-0f911800-ab84-11e8-8060-76417e0755cc.png)
`--scale-character-glyphs-threshold=2.0` and `comment out line 58`:
![image](https://user-images.githubusercontent.com/16748238/44781292-46672e00-ab84-11e8-8830-3e51e803c3b1.png)
Only `comment out line 58`:
![image](https://user-images.githubusercontent.com/16748238/44781398-92b26e00-ab84-11e8-85b0-018b8a98e519.png)

**Comment by ToxicFrog** [comment]
Huh. Those are all pretty bad. :/

I'll download Consolas and do some investigation, but I have limited access to windows so if this is a win10-specific issue rather than a font-specific issue I may have trouble reproducing it.

**Comment by antonovicha** [comment]
Update:
- Problem is still here (I did not regenerated font though)
- I noticed that ligatures is rendered correctly when displayed on screen with scaling of 150% or 200%.
