### ISSUE TITLE
Nothing to be done for '.' when I make

### ISSUE THREAD

**Issue by 619** [ToxicFrog/Ligaturizer#87]
How to reproduce: follow the instructions, error happens at "make ."
OS: MacOS Catalina
Error Message: make: Nothing to be done for `.'.

**Comment by ToxicFrog** [comment]
It's just `make` with no `.` on the end. The . in the documentation is the end of the sentence that the instruction to `make` appears in.

**Comment by 619** [comment]
Why does that sentence need to have a period at the end of it? 🤡Especially with "command" . having a specific meaning (git add .)

**Comment by ToxicFrog** [comment]
Consistency with the others? I think I could just delete the periods from every entry in that list, it just never occurred to me to do so because (On My Machine™) the `commands` are enclosed in grey boxes, clearly separating them from the rest of the text -- perhaps that styling doesn't work in all browsers?
